Follow symlinks and defer debug_assertion evaluation
pyros2097/rust-embed pull request #125
Opened 2020-12-04 00:30 UTC by djmarcin

The large change is refactoring so that rust-embed no longer assumes that it's own compilation flags match those of the expanded code. For example, the proc macro may be compiled in release mode while expanding into code that is compiled in debug mode, or vice versa. This change results in dynamic file lookups when user code is compiled in debug mode, and embedding when compiled in release mode, rather than depending on the compilation of the rust embed proc-macro itself.

The other change included in this PR is to follow symlinks.

Both of these changes are motivated by an attempt to be compatible with the bazel build tool which does not guarantee proc-macro compilation flags match user code compilation flags, and uses symlinks to form a compilation sandbox.

2020-12-05 07:19 UTC, pyros2097 approved these changes
LGTM as along as it works the same and passes all tests

2020-12-05 08:09 UTC, djmarcin commented
> LGTM as along as it works the same and passes all tests

Debug vs non-debug behavior should remain the same, the cfg attributes are just now processed at the time the macro expansion is compiled (e.g. user code) rather than when the proc-macro itself is compiled.

However, following symlinks is a behavior change. I could make the change to put it behind a feature like "follow-symlinks" if you prefer.

2020-12-05 15:53 UTC, Mcat12 requested changes

2020-12-05 15:53 UTC, Mcat12 commented on impl/src/lib.rs
> +  if cfg!(feature = "rust-embed") {
I think this is supposed to be `debug-embed`?

2020-12-05 20:02 UTC, djmarcin commented on impl/src/lib.rs
> +  if cfg!(feature = "rust-embed") {
Good catch, thanks. This fails the tests when I run them manually, but it doesn't look like the tests ran automatically on the PR. All pass now.

2020-12-05 21:04 UTC, Mcat12 commented on impl/src/lib.rs
> +  if cfg!(feature = "rust-embed") {
@pyros2097 is it expected that fork PRs don't run CI?

2020-12-06 15:31 UTC, pyros2097 commented on impl/src/lib.rs
> +  if cfg!(feature = "rust-embed") {
It seems the actions are enabled only on pushes. Will add PR's to it.

2020-12-06 15:49 UTC, pyros2097 commented on impl/src/lib.rs
> +  if cfg!(feature = "rust-embed") {
Yeah all the tests are passing

2020-12-06 16:22 UTC, Mcat12 approved these changes

2020-12-08 11:52 UTC, merged