implement support for multiple include/exclude glob attributes
pyros2097/rust-embed pull request #148
Opened 2021-08-28 15:22 UTC by mbme

Hi!

This PR adds a new feature - `includes-excludes`. With this feature enabled, we can specify multiple attributes with glob values, like `#[include = "*.txt"]` and `#[exclude = "tests/*"]`, for a fine-grained control over files embedded by `rust-embed`.

Example:
```rust
#[derive(RustEmbed)]
#[folder = "examples/public/"]
#[include = "*.html"]
#[include = "images/*"]
#[exclude = "*.txt"]
struct Asset;
```

It is related to #96

2021-08-28 15:54 UTC, mbme commented on tests/metadata.rs
> -  let expected_datetime_utc = 1527818165;
btw I've adjusted the implementation of this test to not to fail on my machine

2021-08-28 18:07 UTC, AzureMarker requested changes
Thanks for working on this! I just have some refactor suggestions and nits.

Run `cargo clippy` to see some more warnings that should be addressed.

2021-08-28 18:07 UTC, AzureMarker commented on impl/src/lib.rs
> +  let embedded_impl = embedded(ident, folder_path.clone(), prefix.as_deref(), includes.clone(), excludes.clone());
Avoid these clones by using references more (`&[String]`).

2021-08-29 11:38 UTC, mbme commented
Thanks for the feedback!
I've implemented suggested changes and addressed clippy warnings.

2021-08-29 21:27 UTC, AzureMarker reviewed
Thanks for the quick update. Just two more spots.

@pyros2097 since this is updating the public API of the utils crate, at least that crate will need a major version bump.

2021-08-29 21:27 UTC, AzureMarker commented on impl/src/lib.rs
> +  };
nit: That works, but this would be simpler:
```rust
let folder_paths = find_attribute_values(ast, "folder");
if folder_paths.len() != 1 {
    panic!("#[derive(RustEmbed)] must contain one attribute like this #[folder = \"examples/public/\"]");
}
let folder_path = folder_paths[0];
```

2021-08-29 21:27 UTC, AzureMarker commented on utils/src/lib.rs
>    return true;
nit: (from clippy) This doesn't need the explicit `return`.

2021-08-30 04:46 UTC, pyros2097 commented on impl/src/lib.rs
> +  };
@AzureMarker  sure can will push a major bump on that crate

2021-08-31 00:12 UTC, AzureMarker approved these changes

2021-08-31 00:12 UTC, AzureMarker commented
Thanks for implementing this!

2021-08-31 00:13 UTC, merged

2021-08-31 04:07 UTC, pyros2097 commented
LGTM. Thanks @mbme.